Feat/34 0608 privileged users page
The-Bugger-Ducks/cloud-fox-web pull request #39
Opened 2022-09-17 08:38 UTC by ThHenrique

#31 #34 

Tela privilégios dos usuários:

![image](https://user-images.githubusercontent.com/58437896/190848204-f3486c73-de16-45e2-9e35-1fc861fe43cb.png)

Tela solicitações de privilégios:

![image](https://user-images.githubusercontent.com/58437896/190848224-06a87f5e-948c-454e-8431-421a91579c66.png)

2022-09-17 14:54 UTC, MariaGabrielaReis requested changes

2022-09-17 14:54 UTC, MariaGabrielaReis commented on src/components/Sidebar/index.tsx
> +      path: "/home",
Por favorzinhooo, alterar o caminho da tela de meu perfil (`/myProfile`) 👉 👈

2022-09-17 14:54 UTC, MariaGabrielaReis commented on src/index.tsx
> +root.render(<App />);
Por que essa alteração de separar os passos?

2022-09-17 14:54 UTC, MariaGabrielaReis commented on src/pages/PrivilegedUsers/index.tsx
> +            SOLICITAÇÕES PRIVILEGIADOS
Sei que no layout o título da página é "SOLICITAÇÕES PRIVILEGIADOS", mas não é estranha essa expressão? Usuários privilegiados ok, pq eles tem mais privilégios que os users simples, but "solicitações privilegiados" não faz muito sentido pra mim. Será que podemos alterar para apenas "SOLICITAÇÕES" ou "SOLICITAÇÕES DE PRIVILÉGIO"?

2022-09-17 19:58 UTC, MariaGabrielaReis requested changes

2022-09-17 19:58 UTC, MariaGabrielaReis commented on src/interfaces/user.interface.ts
> +}
Eu e a Gi estamos criando interfaces mas sem o sufixo ".interface", acha melhor manter ou remover?
Teu PR: `user.interface.ts`
Nossos: `interfaces/user.ts`

2022-09-18 20:57 UTC, ThHenrique commented on src/pages/PrivilegedUsers/index.tsx
> +            SOLICITAÇÕES PRIVILEGIADOS
Concordo contigo, vou fazer essa alteração. Vou deixar SOLICITAÇÕES DE PRIVILÉGIO

2022-09-18 20:58 UTC, ThHenrique commented on src/index.tsx
> +root.render(<App />);
Fiz isso porquê estava dando erro no console.log. Essa alteração está na documentação do React 18 (que é o que estamos utilizando)

2022-09-18 20:58 UTC, ThHenrique commented on src/components/Sidebar/index.tsx
> +      path: "/home",
Claro

2022-09-18 21:00 UTC, ThHenrique commented on src/interfaces/user.interface.ts
> +}
Como vocês já começaram sem o sufixo, acredito que é melhor eu alterar para a padronização de vocês.

2022-09-18 22:24 UTC, MariaGabrielaReis approved these changes

2022-09-19 02:20 UTC, MariaGabrielaReis approved these changes

2022-09-19 02:26 UTC, gioliveirass approved these changes

2022-09-19 02:26 UTC, merged