Feat/0611 #53 role page
The-Bugger-Ducks/cloud-fox-web pull request #62
Opened 2022-10-06 15:54 UTC by ThHenrique

#53 #49 

# Documentação

## Descrição

Para realizar as tasks mencionadas acima foi adicionado no userRequest as rotas de listagem de usuários avançados e rota de atualização de privilégio de um usuário.

## Tecnologias

React, Axios

## Update Role

Para atualização de privilégio foi adicionado trativas de erros onde caso a API venha falhar, o privilégio do usuário é retornado ao anterior e o select fica em foco. 

Caso o privilégio selecionado seja simple, o usuário é retirado da listagem após o final da requisição

## Exemplo de uso

```ts
const onUserRoleChange = async (event: React.ChangeEvent<HTMLSelectElement>, user: User) => {
	const newRole = event.target.value as User["role"];

	try {
		await userRequest.setUserRole(user.id, newRole);

		if (newRole === "simple") {
			setUsers((prevUsers) => {
				return prevUsers.filter((prevUser) => prevUser.id !== user.id);
			});
		}
	} catch (error) {
		event.target.value = user.role;
		event.target.focus();
		alert("Não foi possível alterar o privilégio desse usuário.");
	}
};

```

2022-10-06 21:39 UTC, MariaGabrielaReis requested changes

2022-10-06 21:39 UTC, MariaGabrielaReis commented on src/pages/PrivilegedUsers/index.tsx
> +			alert("Error");
Vale a pena descrever esse alerta aqui, não? Pq vai aparecer pro usuário, colocar alguma mensagem como "Ocorreu um erro ao listar os usuários privilegiados. Tente novamente mais tarde!"

2022-10-06 21:39 UTC, MariaGabrielaReis commented on src/pages/PrivilegedUsers/index.tsx
> +			alert("Error");
Seria legal mudar a mensagem do alert aqui tbmmm

2022-10-06 21:39 UTC, MariaGabrielaReis commented on src/pages/PrivilegedUsers/index.tsx
> +			console.log(error);
Colocar um alert do erro aqui tbm? (pra feedback do usuário)

2022-10-06 21:39 UTC, MariaGabrielaReis commented on src/utils/Requests/user.request.ts
> +		return await api.put('/users/updateRole', { id, role })
Isso daqui não pode dar erro? Não é legal colocar os try catch de requisição direto aqui ao invés de onde vai ser usado essa função? Que aí a gente evita código repetido e pá, dá erro num lugar só kkk

2022-10-06 21:40 UTC, MariaGabrielaReis commented
Inclusive, xuxu, deu ruim no deploy? kkkk

2022-10-07 04:10 UTC, ThHenrique commented on src/pages/PrivilegedUsers/index.tsx
> +			alert("Error");
Bem observado

2022-10-07 04:22 UTC, ThHenrique commented on src/utils/Requests/user.request.ts
> +		return await api.put('/users/updateRole', { id, role })
Vamos ter que testar para verificar se há erros, ainda não encontrei. Eu fiz dessa maneira pq da maneira que estava não retornava o alert

2022-10-07 05:22 UTC, ThHenrique commented
> Inclusive, xuxu, deu ruim no deploy? kkkk

Quando abrimos PR pra development o Netlify realiza essas operações acima, porém o processo de deploy só é realizada quando é feio merge das alterações.

2022-10-09 16:55 UTC, MariaGabrielaReis approved these changes

2022-10-09 17:10 UTC, merged